# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e6bb4bd898431b2294c2cd034105cc02ad8509359117fd0ba99aa07d503de92213bb599f33ffdd99703c6d483283d3d581587d33d5fc63bcf16f40b5c9d9cd42

test:
  secret_key_base: 9f4819720ebf6c54b7bf1e5cd14dc560c914e2a42c1847903eef942fa354be828405d9f49f001a1802daaef6200b4adb1af2a75ea93b0703b53abc9fbbed9dbe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
